# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- stackbit.yaml

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My blog'
description: 'This is my new blog'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=136"

# Pagination
paginate: 5
paginate_path: page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "There isn't much going on here yet, but watch this space"
